# Generated by Django 6.0.7 on 2026-07-28 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('npa_app', '0001_initial'),
        ('recovery_officer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assignment_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('reassigned', 'Reassigned')], default='active', max_length=34)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('npa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='npa_app.npa')),
                ('recovery_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='recovery_officer_app.recoveryofficer')),
            ],
        ),
    ]
