# Generated by Django 6.0.7 on 2026-07-28 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('npa_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoverPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card')], max_length=34)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('npa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='npa_app.npa')),
            ],
        ),
    ]
