# Generated by Django 6.0.7 on 2026-07-27 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npa_date', models.DateField()),
                ('days_past_due', models.PositiveIntegerField()),
                ('npa_category', models.CharField(choices=[('substandard', 'Substandard'), ('doubtful', 'Doubtful'), ('loss', 'Loss Asset')], default='substandard', max_length=24)),
                ('recovery_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('recovered', 'Recovered'), ('closed', 'Closed')], default='pending', max_length=34)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='npa', to='loan_app.loan')),
            ],
        ),
    ]
