# Generated by Django 6.0.7 on 2026-08-12 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npa_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPAStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('npa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='npa_app.npa')),
            ],
        ),
    ]
