# Generated by Django 6.0.7 on 2026-07-27 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_account_number', models.CharField(max_length=45, unique=True)),
                ('loan_type', models.CharField(choices=[('home', 'Home Loan'), ('personal', 'Personal Loan'), ('education', 'Education Loan'), ('vehicle', 'Vehicle Loan'), ('gold', 'Gold Loan'), ('business', 'Business Loan')], max_length=45)),
                ('sanctioned_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenure_months', models.PositiveIntegerField()),
                ('sanction_date', models.DateField()),
                ('loan_status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('npa', 'NPA')], default='active', max_length=34)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='customer_app.customer')),
            ],
        ),
    ]
